#
# Copyright zhigui Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  fabric-grpc:
    container_name: fabric-grpc
    image: zhigui/fabric-grpc:latest
    ports:
      - 8082:8080
    volumes:
      - ./conf:/go/src/fabric-orderer-benchmark/conf
      - ./artifacts/channel:/go/src/fabric-orderer-benchmark/artifacts/channel
      - /tmp/fabric-server-logs:/go/src/fabric-orderer-benchmark/logs