---

application:
  logPath: logs
  logLevel: 7
  local: true
  orderers:
    - name: orderer
      host: orderer.example.com
      port: 7050
  ordererMsp: OrdererMSP
  profile: TwoOrgsOrdererGenesis
  channels:
    - mychannel1
  tlsEnabled: true
  reqTimeout: 120
