---

application:
  logPath: logs
  logLevel: 7
  local: false
  clients: 1
  cpus: 1
  orderers:
    - name: orderer
      host: orderer.example.com
      port: 7050
    - name: orderer
      host: orderer2.example.com
      port: 7050
    - name: orderer
      host: orderer3.example.com
      port: 7050
    - name: orderer
      host: orderer4.example.com
      port: 7050
  ordererMsp: OrdererMSP
  profile: TwoOrgsOrdererGenesis #departed
  channels:
    - mychannel
  tlsEnabled: true
  reqTimeout: 120
